### LIST ALL INGREDIENTS
GET http://localhost:8000/api/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0ODA2OSwiZXhwIjoxNjA0NDUxNjY5fQ.h2gjjk6vhN3NdxWDWXc5zcQQxtlAWpJ5VcIrjbkumM0

### LIST ONE INGREDIENT
GET http://localhost:8000/api/ingredients/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0ODA2OSwiZXhwIjoxNjA0NDUxNjY5fQ.h2gjjk6vhN3NdxWDWXc5zcQQxtlAWpJ5VcIrjbkumM0

### CREATE INGREDIENT
POST http://localhost:8000/api/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0ODA2OSwiZXhwIjoxNjA0NDUxNjY5fQ.h2gjjk6vhN3NdxWDWXc5zcQQxtlAWpJ5VcIrjbkumM0
Content-Type: application/json

{
  "name": "leite", 
  "description": "leite descricao"
}

### UPDATE INGREDIENT
PUT http://localhost:8000/api/ingredients/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0ODA2OSwiZXhwIjoxNjA0NDUxNjY5fQ.h2gjjk6vhN3NdxWDWXc5zcQQxtlAWpJ5VcIrjbkumM0
Content-Type: application/json

{
  "name": "leite modify", 
  "description": "leite descricao modify",
  "active": 1
}

### DELETE INGREDIENT
DELETE http://localhost:8000/api/ingredients/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0ODA2OSwiZXhwIjoxNjA0NDUxNjY5fQ.h2gjjk6vhN3NdxWDWXc5zcQQxtlAWpJ5VcIrjbkumM0
