### LOGIN
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "username": "admin", 
  "password": "admin"
}

### REFRESH TOKEN
POST http://localhost:8000/api/refresh
Content-Type: application/json

{
  "username": "admin", 
  "password": "admin",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzY0NCwiZXhwIjoxNjA0NDU4NDQ0fQ.6kiNG1s6gCbLhOxPgbF1-ejiQyiU9zoRLbv-5TwwB3g"
}

### LOGOUT
POST http://localhost:8000/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzY1NSwiZXhwIjoxNjA0NDUxMjU1fQ.UPpwAbKX7FAV1Uqm4FeQaG0bQeXLX0zs63Q6s8gMml4

