### LIST ALL RECIPES
GET http://localhost:8000/api/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRPd0U5Mng3MjUyblh3Z3lCSU96ckF1MjB3RDFWQUQyMWh1ZXguT2RNYm5EelgvZTdvdGpqRyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDM1OTQyMCwiZXhwIjoxNjA0MzYxMjIwfQ.-uI1SR1uvSbLCWxMMeE49wbGfDPh8nGSaG_HmbPkYCA

### LIST ONE RECIPE
GET http://localhost:8000/api/recipes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRPd0U5Mng3MjUyblh3Z3lCSU96ckF1MjB3RDFWQUQyMWh1ZXguT2RNYm5EelgvZTdvdGpqRyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDM1NTE4NywiZXhwIjoxNjA0MzU2OTg3fQ.PZot67T5GgSI6RDun6GTbryQMecrmjpEd2Qh_HU1zJk

### CREATE RECIPE
POST http://localhost:8000/api/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRPd0U5Mng3MjUyblh3Z3lCSU96ckF1MjB3RDFWQUQyMWh1ZXguT2RNYm5EelgvZTdvdGpqRyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDM2NDA4NCwiZXhwIjoxNjA0MzY3Njg0fQ.yPWw9WthNjYzaB_GNmvIG7jmIBjNBqRLyrBJ41gqrrQ
Content-Type: application/json

{
  "name": "bolo", 
  "description": "bolo descricao",
  "ingredientsList": [{"id":9}]
}

### UPDATE RECIPE
PUT http://localhost:8000/api/recipes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRPd0U5Mng3MjUyblh3Z3lCSU96ckF1MjB3RDFWQUQyMWh1ZXguT2RNYm5EelgvZTdvdGpqRyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDM2MzI5OCwiZXhwIjoxNjA0MzY2ODk4fQ.fqZOgukovPWIgZkWccIDETH4yhbknOHIOET88oeNJwM
Content-Type: application/json

{
  "name": "nova receita", 
  "description": "nova receitass descricao",
  "ingredientsList": [{"id":5}, {"id":7}]
}

### DELETE RECIPE
DELETE http://localhost:8000/api/recipes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRPd0U5Mng3MjUyblh3Z3lCSU96ckF1MjB3RDFWQUQyMWh1ZXguT2RNYm5EelgvZTdvdGpqRyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDM1NTE4NywiZXhwIjoxNjA0MzU2OTg3fQ.PZot67T5GgSI6RDun6GTbryQMecrmjpEd2Qh_HU1zJk
