### LIST ALL USERS
GET http://localhost:8000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzMyMiwiZXhwIjoxNjA0NDUwOTIyfQ.I8OaixSAnqtXQjjbSoAdOharxxboJ3L77Q9Iidyx9MU

### LIST ONE USER
GET http://localhost:8000/api/users/54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJuYW1lIjpudWxsLCJpYXQiOjE2MTA0ODQyODUsImV4cCI6MTYxMDQ4Nzg4NX0.OJQtFhJ5rXpcRnz3fyMY6du7KBiNko2xNR-9c4oNhmU

### CREATE USER
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "username": "ruben", 
  "password": "ruben"
}

### UPDATE USER
PUT http://localhost:8000/api/users/55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzMyMiwiZXhwIjoxNjA0NDUwOTIyfQ.I8OaixSAnqtXQjjbSoAdOharxxboJ3L77Q9Iidyx9MU
Content-Type: application/json

{
  "username": "ruben_carreira", 
  "password": "ruben carreira",
  "name": "ruben carreira"
}

### DELETE USER
DELETE http://localhost:8000/api/users/55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzMyMiwiZXhwIjoxNjA0NDUwOTIyfQ.I8OaixSAnqtXQjjbSoAdOharxxboJ3L77Q9Iidyx9MU

### AVAILABLE USER
DELETE http://localhost:8000/api/users/available/56
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsInVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYiQxMCRBTUY2VEZpV2lvNFh4NDQvRjdMU2IuMVR2WG5RL3JLRVdrTEtzNVpHOTB0Rk9Sa3RQSjN4TyIsIm5hbWUiOm51bGwsImlhdCI6MTYwNDQ0NzMyMiwiZXhwIjoxNjA0NDUwOTIyfQ.I8OaixSAnqtXQjjbSoAdOharxxboJ3L77Q9Iidyx9MU
Content-Type: application/json

{
  "active": false
}